x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_URL: postgres://tongstongs:tongstongs@db:5432/tongstongs

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tongstongs
      POSTGRES_PASSWORD: tongstongs
      POSTGRES_DB: tongstongs
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

volumes:
  db_data:
